// mc_klt — train the 3D-LFNST secondary transform: KLT of the 4x4x4 low-band
// DCT corner over a corpus, printed as a Q14 i16 matrix for src/mc_klt_tab.h.
// usage: mc_klt <vol.bin[,vol2,...]> <dim>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <math.h>
#include "../src/mc_codec.c"

#define KN 64   // 4x4x4 corner

// corner positions sorted by (L1 band, raster) — must match the codec exactly.
static int corner_idx[KN];
static void corner_build(void){
    int n=0;
    for(int b=0;b<=9;++b)
        for(int cz=0;cz<4;++cz)for(int cy=0;cy<4;++cy)for(int cx=0;cx<4;++cx)
            if(cz+cy+cx==b) corner_idx[n++]=(cz*MC_BLK+cy)*MC_BLK+cx;
}

// Jacobi eigensolver for symmetric KN x KN (descending eigenvalues)
static void jacobi(double *A, double *V, double *ev){
    for(int i=0;i<KN;++i)for(int j=0;j<KN;++j) V[i*KN+j]=(i==j);
    for(int sweep=0;sweep<100;++sweep){
        double off=0;
        for(int p=0;p<KN;++p)for(int q=p+1;q<KN;++q) off+=A[p*KN+q]*A[p*KN+q];
        if(off<1e-9) break;
        for(int p=0;p<KN;++p)for(int q=p+1;q<KN;++q){
            double apq=A[p*KN+q]; if(fabs(apq)<1e-12) continue;
            double app=A[p*KN+p], aqq=A[q*KN+q];
            double th=0.5*(aqq-app)/apq;
            double t=(th>=0?1.0:-1.0)/(fabs(th)+sqrt(th*th+1.0));
            double c=1.0/sqrt(t*t+1.0), s=t*c;
            for(int k=0;k<KN;++k){
                double akp=A[k*KN+p], akq=A[k*KN+q];
                A[k*KN+p]=c*akp-s*akq; A[k*KN+q]=s*akp+c*akq;
            }
            for(int k=0;k<KN;++k){
                double apk=A[p*KN+k], aqk=A[q*KN+k];
                A[p*KN+k]=c*apk-s*aqk; A[q*KN+k]=s*apk+c*aqk;
            }
            for(int k=0;k<KN;++k){
                double vkp=V[k*KN+p], vkq=V[k*KN+q];
                V[k*KN+p]=c*vkp-s*vkq; V[k*KN+q]=s*vkp+c*vkq;
            }
        }
    }
    for(int i=0;i<KN;++i) ev[i]=A[i*KN+i];
    // sort descending by eigenvalue (columns of V)
    for(int i=0;i<KN;++i)for(int j=i+1;j<KN;++j) if(ev[j]>ev[i]){
        double t=ev[i];ev[i]=ev[j];ev[j]=t;
        for(int k=0;k<KN;++k){ double v=V[k*KN+i]; V[k*KN+i]=V[k*KN+j]; V[k*KN+j]=v; }
    }
}

int main(int argc,char**argv){
    if(argc<3){ fprintf(stderr,"usage: %s <vol.bin[,vol2]> <dim>\n",argv[0]); return 1; }
    int D=atoi(argv[2]); size_t n=(size_t)D*D*D;
    mc_codec_init(); corner_build();
    static double cov[KN*KN]; static double mean[KN]; long ns=0;
    static mc_u8 vox[N3]; static float blkf[N3], coef[N3];
    char *vv=strdup(argv[1]);
    for(char *vp=strtok(vv,",");vp;vp=strtok(NULL,",")){
        mc_u8 *vol=malloc(n);
        FILE*f=fopen(vp,"rb"); if(!f){perror(vp);return 1;}
        if(fread(vol,1,n,f)!=n){fprintf(stderr,"short\n");return 1;} fclose(f);
        for(int bz=0;bz+MC_BLK<=D;bz+=MC_BLK)
        for(int by=0;by+MC_BLK<=D;by+=MC_BLK)
        for(int bx=0;bx+MC_BLK<=D;bx+=MC_BLK){
            int any=0;
            for(int z=0;z<MC_BLK;++z)for(int y=0;y<MC_BLK;++y)
                memcpy(vox+((size_t)z*MC_BLK+y)*MC_BLK, vol+((size_t)(bz+z)*D+(by+y))*D+bx, MC_BLK);
            for(int i=0;i<N3;++i) any|=vox[i];
            if(!any) continue;
            long sum=0,cnt=0; for(int i=0;i<N3;++i){ if(vox[i]){sum+=vox[i];cnt++;} }
            int dc=(int)((sum+cnt/2)/cnt);
            for(int i=0;i<N3;++i) blkf[i]=(float)((vox[i]?vox[i]:dc)-dc);
            mc_dct3_fwd(blkf,coef);
            double v[KN];
            for(int i=0;i<KN;++i) v[i]=coef[corner_idx[i]];
            for(int i=0;i<KN;++i){ mean[i]+=v[i];
                for(int j=0;j<KN;++j) cov[i*KN+j]+=v[i]*v[j]; }
            ns++;
        }
        free(vol);
    }
    for(int i=0;i<KN;++i)for(int j=0;j<KN;++j)
        cov[i*KN+j]=cov[i*KN+j]/ns - (mean[i]/ns)*(mean[j]/ns);
    static double V[KN*KN], ev[KN];
    jacobi(cov,V,ev);
    fprintf(stderr,"samples %ld; top eigenvalues:",ns);
    for(int i=0;i<8;++i) fprintf(stderr," %.0f",ev[i]);
    fprintf(stderr," ... tail:");
    for(int i=KN-4;i<KN;++i) fprintf(stderr," %.1f",ev[i]);
    fprintf(stderr,"\n");
    // K[i][j]: output i = sum_j K[i][j] * corner[j]  (rows = eigenvectors^T)
    printf("// generated by tools/mc_klt — 3D-LFNST secondary transform (Q14),\n");
    printf("// KLT of the 4x4x4 low-band DCT corner, trained on PHercParis4 2.4um.\n");
    printf("static const int16_t MC_KLT[64][64]={\n");
    for(int i=0;i<KN;++i){
        printf("{");
        for(int j=0;j<KN;++j){
            int q=(int)lround(V[j*KN+i]*16384.0);
            if(q>32767)q=32767; if(q<-32768)q=-32768;
            printf("%d%s",q,j<KN-1?",":"");
        }
        printf("}%s\n",i<KN-1?",":"");
    }
    printf("};\n");
    return 0;
}
