// mc_rans_tab — train the static per-band rANS symbol tables for the HF
// coefficient stage (scan positions >= 64). Prints src/mc_rans_tab.h:
// freq[4 q-buckets][8 bands][65 syms] normalized to 4096.
// usage: mc_rans_tab <vol.bin[,vol2]> <dim>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <math.h>
#include "../src/mc_codec.c"

static inline uint32_t zigzag32(int32_t v){ return (uint32_t)((v<<1)^(v>>31)); }
static double hist[4][NB_BANDS][65];
static const float QB[4]={1.0f,3.0f,6.0f,12.0f};

int main(int argc,char**argv){
    if(argc<3){ fprintf(stderr,"usage: %s <vol.bin[,vol2]> <dim>\n",argv[0]); return 1; }
    int D=atoi(argv[2]); size_t n=(size_t)D*D*D;
    mc_codec_init();
    scanS_build(MC_BLK); const uint16_t *scan=g_scanS[4];
    static mc_u8 vox[N3]; static float blkf[N3], coef[N3]; static rc_i16 ql[N3];
    for(int qb=0;qb<4;++qb){
        mc_set_quality(QB[qb]);
        char *vv=strdup(argv[1]);
        for(char *vp=strtok(vv,",");vp;vp=strtok(NULL,",")){
            mc_u8 *vol=malloc(n);
            FILE*f=fopen(vp,"rb"); if(!f){perror(vp);return 1;}
            if(fread(vol,1,n,f)!=n){fprintf(stderr,"short\n");return 1;} fclose(f);
            for(int bz=0;bz+MC_BLK<=D;bz+=MC_BLK)
            for(int by=0;by+MC_BLK<=D;by+=MC_BLK)
            for(int bx=0;bx+MC_BLK<=D;bx+=MC_BLK){
                int any=0;
                for(int z=0;z<MC_BLK;++z)for(int y=0;y<MC_BLK;++y)
                    memcpy(vox+((size_t)z*MC_BLK+y)*MC_BLK, vol+((size_t)(bz+z)*D+(by+y))*D+bx, MC_BLK);
                for(int i=0;i<N3;++i) any|=vox[i];
                if(!any) continue;
                long sum=0,cnt=0; for(int i=0;i<N3;++i){ if(vox[i]){sum+=vox[i];cnt++;} }
                int dc=(int)((sum+cnt/2)/cnt);
                for(int i=0;i<N3;++i) blkf[i]=(float)((vox[i]?vox[i]:dc)-dc);
                mc_dct3_fwd(blkf,coef);
                step_tab_build();
                for(int i=0;i<N3;++i) ql[i]=(rc_i16)quant_one(coef[i],g_step_tab[i]);
                rc_u32 eob=0; for(rc_u32 p=N3;p-->0;){ if(ql[scan[p]]){eob=p+1;break;} }
                for(rc_u32 p=64;p<eob;++p){
                    rc_u32 idx=scan[p]; int b=band_of_S(idx,MC_BLK);
                    uint32_t zz=zigzag32(ql[idx]);
                    hist[qb][b][zz<64?zz:64]+=1.0;
                }
            }
            free(vol);
        }
        free(vv);
        fprintf(stderr,"q=%g done\n",QB[qb]);
    }
    printf("// generated by tools/mc_rans_tab — static HF symbol frequencies\n");
    printf("// (zigzag level 0..63 + escape) per q-bucket x band, sum = 4096.\n");
    printf("static const uint16_t MC_RANS_FREQ[4][8][65]={\n");
    for(int qb=0;qb<4;++qb){
        printf("{ // q-bucket %d (~q=%g)\n",qb,QB[qb]);
        for(int b=0;b<NB_BANDS;++b){
            double tot=0; for(int s=0;s<65;++s) tot+=hist[qb][b][s]+0.25;
            uint32_t acc=0; uint16_t fr[65];
            for(int s=0;s<65;++s){ uint32_t f=(uint32_t)((hist[qb][b][s]+0.25)/tot*4096.0);
                if(f<1)f=1; fr[s]=(uint16_t)f; acc+=f; }
            int mx=0; for(int s=1;s<65;++s) if(fr[s]>fr[mx])mx=s;
            fr[mx]=(uint16_t)(fr[mx]+(int)(4096-acc));
            printf("  {");
            for(int s=0;s<65;++s) printf("%u%s",fr[s],s<64?",":"");
            printf("}%s\n",b<NB_BANDS-1?",":"");
        }
        printf("}%s\n",qb<3?",":"");
    }
    printf("};\n");
    return 0;
}
